seccion:
    path:     /
    defaults: { _controller: "DeteccionBundle:Seccion:index" }

seccion_show:
    path:     /{id}/show
    defaults: { _controller: "DeteccionBundle:Seccion:show" }

seccion_new:
    path:     /new
    defaults: { _controller: "DeteccionBundle:Seccion:new" }

seccion_create:
    path:     /create
    defaults: { _controller: "DeteccionBundle:Seccion:create" }
    methods:  POST

seccion_edit:
    path:     /{id}/edit
    defaults: { _controller: "DeteccionBundle:Seccion:edit" }

seccion_update:
    path:     /{id}/update
    defaults: { _controller: "DeteccionBundle:Seccion:update" }
    methods:  [POST, PUT]

seccion_delete:
    path:     /{id}/delete
    defaults: { _controller: "DeteccionBundle:Seccion:delete" }
    methods:  [POST, DELETE]
