<?php

namespace DeteccionBundle\Repository;

/**
 * AplicativoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AplicativoRepository extends \Doctrine\ORM\EntityRepository
{
}
