<?php

namespace DeteccionBundle\Repository;
set_time_limit(300);
/**
 * Conf_sistemaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Conf_sistemaRepository extends \Doctrine\ORM\EntityRepository
{
	public function obtenerConf($direccion)
	{
		function ejecutar($comando)
        {
            //Ejecutando el comando MS-DOS
            $respuesta=shell_exec($comando);
            //Determinar la posicion del =
            $posicion=strpos($respuesta, '=');
            //retornamos todo lo que este DESPUES del igual
            return substr($respuesta, ($posicion+1));
        }

        $res['nso'] = ejecutar("WMIC $direccion OS get  Caption /FORMAT:List");
        $res['vso'] = ejecutar("WMIC $direccion OS get  Version /FORMAT:List");
        $res['aso'] = ejecutar("WMIC $direccion OS get  OSArchitecture /FORMAT:List");

        return $res;
	}
}
