<?php

namespace DeteccionBundle\Repository;

/**
 * Conf_redRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Conf_redRepository extends \Doctrine\ORM\EntityRepository
{
}
