<?php

namespace DeteccionBundle\Repository;

/**
 * DeteccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeteccionRepository extends \Doctrine\ORM\EntityRepository
{	
	public function ejecutar($comando)
    {
        //Ejecutando el comando MS-DOS
        $respuesta=shell_exec($comando);
        //Determinar la posicion del =
        $posicion=strpos($respuesta, '=');
        //retornamos todo lo que este DESPUES del igual
        return substr($respuesta, ($posicion+1));
    }
    public function reemplazar($bus,$ree, $cadena)
    {
    	str_replace($bus, $ree, $cadena);
    }
}
