<?php

namespace DeteccionBundle\Repository;

/**
 * MemoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemoriaRepository extends \Doctrine\ORM\EntityRepository
{
	public function obtenerMemoria($direccion)
	{
		//***temporallllllllllllllllllllllllllllll
		$direccion=null;
		//Determinar el # de Memorias
		$cant=ejecutar("WMIC $direccion MEMPHYSICAL get MemoryDevices /FORMAT:List");
		
		if ($cant>"1") {

			for ($f=0; $f < $cant; $f++) {
					$res[$f]['ser'] = $this->ejecutar("WMIC $direccion memoryChip WHERE Tag='Physical Memory ".$f."' get SerialNumber /FORMAT:List");
					$res[$f]['mar'] = $this->ejecutar("WMIC $direccion memoryChip WHERE Tag='Physical Memory ".$f."' get Manufacturer /FORMAT:List");
					$res[$f]['cap'] = $this->ejecutar("WMIC $direccion memoryChip WHERE Tag='Physical Memory ".$f."' get Capacity /FORMAT:List");
					$res[$f]['vel'] = $this->ejecutar("WMIC $direccion memoryChip WHERE Tag='Physical Memory ".$f."' get Speed /FORMAT:List");
					$res[$f]['tip'] = $this->ejecutar("WMIC $direccion memoryChip WHERE Tag='Physical Memory ".$f."' get MemoryType /FORMAT:List");
			}	
		} else {
			$res['ser'] = $this->ejecutar("WMIC $direccion memoryChip get SerialNumber /FORMAT:List");
			$res['mar'] = $this->ejecutar("WMIC $direccion memoryChip get Manufacturer /FORMAT:List");
			$res['cap'] = $this->ejecutar("WMIC $direccion memoryChip get Capacity /FORMAT:List");
			$res['vel'] = $this->ejecutar("WMIC $direccion memoryChip get Speed /FORMAT:List");
			$res['tip'] = $this->ejecutar("WMIC $direccion memoryChip get MemoryType /FORMAT:List");
		}        
        return $res;
	}
	public function ejecutar($comando){
        //Ejecutando el comando MS-DOS
        $respuesta=shell_exec($comando);
        //Determinar la posicion del =
        $posicion=strpos($respuesta, '=');
        //retornamos todo lo que este DESPUES del igual
        return substr($respuesta, ($posicion+1));
    }
}

