<?php

namespace DeteccionBundle\Repository;

/**
 * SoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoRepository extends \Doctrine\ORM\EntityRepository
{
}
